### ISSUE TITLE
Unexpected result

### ISSUE THREAD

**Issue by Talhaali50** [gnaneshwar441/Business_Duration#2]
Hi, 

I applied your package to my calculation and it gave some unexpected results for certain dates which I am unable to figure out why for e.g :

start_date = pd.to_datetime('2019-06-08 23:07:02.882802')  # 8th and 9th was a weekend 
end_date = pd.to_datetime('2019-06-11 02:53:20.901426')

print(businessDuration(startdate=start_date,enddate=end_date,starttime=None,endtime=None,holidaylist=None,unit='sec'))

# This gives below result in sec's
>>>  13578

It skipped June 10th completely which is Monday and working day not sure why. If I change the start date to :
start_date = pd.to_datetime('2019-06-10 00:00:00.882802')

Than it gives the correct result :

>>> 96800

Can you have a look at this and advice what is happening here.

Thank You

**Comment by gnaneshwar441** [comment]
This issue is resolved in the new version. Kindly use business-duration 0.63
