### ISSUE TITLE
NaN when events start and end on non-business days

### ISSUE THREAD

**Issue by adi-** [gnaneshwar441/Business_Duration#3]
When `datetime_finished=2020-01-05` `datetime_started=2020-01-05` (sunday) businessDuration(startdate=datetime_finished, enddate=datetime_started) returns `NaN`. There should be built-in workaround.

**Comment by gnaneshwar441** [comment]
Thanks for your feedback. This will be fixed in next version.

**Comment by gnaneshwar441** [comment]
This issue is resolved in the new version. Kindly use "business-duration 0.62".

**Comment by adi-** [comment]
Nice! Thank you.
