### ISSUE TITLE
Incorrect holidays usage on example

### ISSUE THREAD

**Issue by rsupr** [gnaneshwar441/Business_Duration#4]
I have trying to use this module with custom holidays and followed your [EXAMPLE](https://github.com/gnaneshwar441/Business_Duration#example-3), but I found that the holidayList parameter was not functional.

It turns out that the holidayList must be in `datetime.date` format, not `datetime.datetime`

**Comment by gnaneshwar441** [comment]
datetime.datetime is replaced with datetime.date in the EXAMPLE. Kindly refer version 0.64.
Thanks
