### ISSUE TITLE
Increasing speed of calculation

### ISSUE THREAD

**Issue by hatawab** [gnaneshwar441/Business_Duration#5]
Hi @gnaneshwar441

I'm using this library for one of my projects, but I noticed that it is slow, especially if there is a large difference between the start date and end date.

I think the primary reason for this is the for-loop in lines 28-30 which you use to create the initial list of working days (before removing public holidays and weekends).

Instead of this:
```
deltatime = enddate.date()-startdate.date()
        days_diff = deltatime.days
        working_days = []
        for i in range(0,days_diff+1):
            tmp = pd.to_datetime(startdate+timedelta(i)).date()
            working_days.append(tmp)
```
I would suggest used the vectorized pandas function:
`working_days = pd.date_range(start=startdate.date(), end=enddate.date(), freq='D').to_list()`

Thanks,
Hasan

**Comment by gnaneshwar441** [comment]
Hello Hasan,

pd.date_range() returns 'datetime64[ns]' type whereas I'm trying to convert it to 'datetime.date' type. So 'for' loop is used here. Besides, even if we consider using pd.date_range() I'll still have to loop it to convert it to 'datetime.date' which in turn consumes more execution time. 
I had already thought about your approach before considering this approach.

Let me know if there is anything I may help you with before I close this issue

**Comment by gnaneshwar441** [comment]
Closing this incident

**Comment by gnaneshwar441** [comment]
Closing PR
