### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by andrewtmendoza** [gnaneshwar441/Business_Duration#6]
Hello - the code works but it seems to be raising a pandas error:

```
import pendulum
from datetime import time
from business_duration import businessDuration


biz_hours = {
    "AMER": (time(8,0,0,0,pendulum.timezone("America/New_York")), time(20,0,0,0,pendulum.timezone("America/New_York"))),
    "EMEA": (time(8,0,0,0,pendulum.timezone("Europe/London")), time(17,0,0,0,pendulum.timezone("Europe/London"))),
    "APAC": (time(8,0,0,0,pendulum.timezone("Australia/Sydney")), time(19,0,0,0,pendulum.timezone("Australia/Sydney"))),
}

opened = pendulum.instance(datetime.datetime(2020, 3, 16, 12, 42, 7), tz="America/Los_Angeles")
responded = pendulum.instance(datetime.datetime(2020, 3, 16, 13, 53, 40), tz="America/Los_Angeles")
start, stop = biz_hours["AMER"]
print(businessDuration(startdate=opened,enddate=responded,starttime=start,endtime=stop,unit="hour"))
```

> In [9]: print(businessDuration(startdate=opened,enddate=responded,starttime=start,endtime=stop,unit="hour"))
> Traceback (most recent call last):
> 
>   File "pandas\_libs\tslibs\timezones.pyx", line 266, in pandas._libs.tslibs.timezones.get_dst_info
> 
> AttributeError: 'NoneType' object has no attribute 'total_seconds'
> 
> Exception ignored in: 'pandas._libs.tslibs.conversion._localize_tso'
> Traceback (most recent call last):
>   File "pandas\_libs\tslibs\timezones.pyx", line 266, in pandas._libs.tslibs.timezones.get_dst_info
> AttributeError: 'NoneType' object has no attribute 'total_seconds'
> Out[9]: 1.1925

Pandas == 1.3.2

**Comment by andrewtmendoza** [comment]
This seems to be a workaround https://github.com/pandas-dev/pandas/issues/15986#issuecomment-702745405

**Comment by gnaneshwar441** [comment]
Hello Andrew,
`startdate `and `enddate `must follow `Timestamp `type
`starttime `and `endtime `must follow `datetime.time` type
As long as these types are maintained you'll not see any errors.
Since you are using an external package ('pendulum') for timezone kindly follow the workaround as you suggested.
Hence closing this issue
