### ISSUE TITLE
Bug on length of one working day

### ISSUE THREAD

**Issue by wilsonn-g** [gnaneshwar441/Business_Duration#7]
Hi, thanks for sharing this project.

While doing some quick tests I noticed that given overnight business hours, an incorrect business duration is returned for a length of one work day.

Ex.
```
# Corresponds to 5PM - 1AM business hours
OPEN_TIME=time(17,0,0)
CLOSE_TIME=time(1,0,0)

# Event occurs from 2AM-4:48AM (outside of business hours)
start_date = pd.to_datetime('2021-11-15 02:00:00')
end_date = pd.to_datetime('2021-11-15 04:48:00')

print(businessDuration(start_date, end_date, OPEN_TIME, CLOSE_TIME, unit = 'hour'))
```
The expected result is 0 hours, however, the function returns a duration of 8 hours.

**Comment by gnaneshwar441** [comment]
Thanks @wilsonn-g for pointing the bug. It is resolved now.
Please upgrade your library to new version - business-duration (0.65)

**Comment by gnaneshwar441** [comment]
Thanks @wilsonn-g for pointing the bug. It is resolved now.
Please upgrade your library to new version - business-duration (0.65)
