### ISSUE TITLE
Issue while calculating number of days, hours and minutes

### ISSUE THREAD

**Issue by tusharsnl** [gnaneshwar441/Business_Duration#8]
#Business duration can be 'day', 'hour', 'min', 'sec'
unit_min='min'
unit_day='day'

#Business open hour must be in standard python time format-Hour,Min,Sec
biz_open_time=datetime.time(0,0,0)

#Business close hour must be in standard python time format-Hour,Min,Sec
biz_close_time=datetime.time(23,59,59)

in_holidays = holidays.HolidayBase()
in_holidays.append('2021-01-01')

opened_at = pd.to_datetime('2021-01-01 11:10:43', format='%Y-%m-%d %H:%M:%S')
end_date = pd.to_datetime('2021-01-05 10:45:41', format='%Y-%m-%d %H:%M:%S')

days = businessDuration(startdate=opened_at, enddate=end_date, starttime=biz_open_time,
                                endtime=biz_close_time, holidaylist=in_holidays, unit=unit_day)

print(days)

minutes = businessDuration(startdate=opened_at, enddate=end_date, starttime=biz_open_time,
                                   endtime=biz_close_time, holidaylist=in_holidays, unit=unit_min)

print(minutes//60)

**************************************

for this code it is giving 23 hour difference instead it should have given around 34 hours

**Comment by gnaneshwar441** [comment]
@tusharsnl - Issue while calculating number of days, hours and minutes is fixed.
